services:
  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: build/package/gateway/Dockerfile
    profiles: ["app"]
    ports:
      - "8080:8080"
    networks:
      - merch-net
    env_file:
      - .env
    depends_on:
      auth:
        condition: service_started
      store:
        condition: service_started
      postgres:
        condition: service_healthy

  auth:
    container_name: auth
    build:
      context: .
      dockerfile: build/package/auth/Dockerfile
    profiles: ["app"]
    ports:
      - "9090:9090"
    networks:
      - merch-net
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  store:
    container_name: store
    build:
      context: .
      dockerfile: build/package/store/Dockerfile
    profiles: ["app"]
    ports:
      - "9091:9091"
    networks:
      - merch-net
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: "postgres:16-alpine"
    profiles: ["app", "infra"]
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: merch_store_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - merch-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d merch_store_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

networks:
  merch-net:
    driver: bridge

volumes:
  postgres_data:
