services:
  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: build/package/gateway/Dockerfile
    profiles: ["app"]
    ports:
      - "8080:8080"
    networks:
      - merch-net
    env_file:
      - .env
    depends_on:
      auth:
        condition: service_started
      store:
        condition: service_started

  auth:
    container_name: auth
    build:
      context: .
      dockerfile: build/package/auth/Dockerfile
    profiles: ["app"]
    ports:
      - "9090:9090"
    networks:
      - merch-net
    env_file:
      - .env
    depends_on:
      auth-migrator:
        condition: service_completed_successfully

  store:
    container_name: store
    build:
      context: .
      dockerfile: build/package/store/Dockerfile
    profiles: ["app"]
    ports:
      - "9091:9091"
    networks:
      - merch-net
    env_file:
      - .env
    depends_on:
      store-migrator:
        condition: service_completed_successfully

  auth-migrator:
    image: "gomicro/goose"
    volumes:
      - ./migrations/auth:/migrations
    profiles: ["app", "infra"]
    networks:
      - merch-net
    command: /bin/goose postgres "postgres://${DB_AUTH_USER}:${DB_AUTH_PASSWORD}@postgres-auth:5432/${DB_AUTH_NAME}?sslmode=disable" up
    depends_on:
      postgres-auth:
        condition: service_healthy

  store-migrator:
    image: "gomicro/goose"
    volumes:
      - ./migrations/store:/migrations
    profiles: [ "app", "infra" ]
    networks:
      - merch-net
    command: /bin/goose postgres "postgres://${DB_STORE_USER}:${DB_STORE_PASSWORD}@postgres-store:5432/${DB_STORE_NAME}?sslmode=disable" up
    depends_on:
      postgres-store:
        condition: service_healthy

  postgres-auth:
    image: "postgres:16-alpine"
    profiles: ["app", "infra"]
    environment:
      POSTGRES_USER: ${DB_AUTH_USER}
      POSTGRES_PASSWORD: ${DB_AUTH_PASSWORD}
      POSTGRES_DB: ${DB_AUTH_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    networks:
      - merch-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_AUTH_USER} -d ${DB_AUTH_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  postgres-store:
    image: "postgres:16-alpine"
    profiles: [ "app", "infra" ]
    environment:
      POSTGRES_USER: ${DB_STORE_USER}
      POSTGRES_PASSWORD: ${DB_STORE_PASSWORD}
      POSTGRES_DB: ${DB_STORE_NAME}
    ports:
      - "5434:5432"
    volumes:
      - postgres_store_data:/var/lib/postgresql/data
    networks:
      - merch-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_STORE_USER} -d ${DB_STORE_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

networks:
  merch-net:
    driver: bridge

volumes:
  postgres_auth_data:
  postgres_store_data:
