services:
  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: build/package/gateway/Dockerfile
    profiles: ["app"]
    ports:
      - "8080:8080"
    networks:
      - merch-net
    env_file:
      - .env
    depends_on:
      auth:
        condition: service_started
      store:
        condition: service_started

  auth:
    container_name: auth
    build:
      context: .
      dockerfile: build/package/auth/Dockerfile
    profiles: ["app"]
    ports:
      - "9090:9090"
    networks:
      - merch-net
    env_file:
      - .env
    depends_on:
      auth-migrator:
        condition: service_completed_successfully

  store:
    container_name: store
    build:
      context: .
      dockerfile: build/package/store/Dockerfile
    profiles: ["app"]
    ports:
      - "9091:9091"
    networks:
      - merch-net
    env_file:
      - .env
    depends_on:
      store-migrator:
        condition: service_completed_successfully

  auth-migrator:
    image: "gomicro/goose"
    volumes:
      - ./migrations/auth:/migrations
    profiles: ["app", "infra"]
    networks:
      - merch-net
    command: /bin/goose postgres "postgres://auth_admin:auth_password@postgres-auth:5432/merch_auth_db?sslmode=disable" up
    depends_on:
      postgres-auth:
        condition: service_healthy

  store-migrator:
    image: "gomicro/goose"
    volumes:
      - ./migrations/store:/migrations
    profiles: [ "app", "infra" ]
    networks:
      - merch-net
    command: /bin/goose postgres "postgres://store_admin:store_password@postgres-store:5432/merch_store_db?sslmode=disable" up
    depends_on:
      postgres-store:
        condition: service_healthy

  postgres-auth:
    image: "postgres:16-alpine"
    profiles: ["app", "infra"]
    environment:
      POSTGRES_USER: auth_admin
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: merch_auth_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    networks:
      - merch-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_admin -d merch_auth_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  postgres-store:
    image: "postgres:16-alpine"
    profiles: [ "app", "infra" ]
    environment:
      POSTGRES_USER: store_admin
      POSTGRES_PASSWORD: store_password
      POSTGRES_DB: merch_store_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_store_data:/var/lib/postgresql/data
    networks:
      - merch-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U store_admin -d merch_store_db" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

networks:
  merch-net:
    driver: bridge

volumes:
  postgres_auth_data:
  postgres_store_data:
