apiVersion: v1
kind: Secret
metadata:
  name: merch-secrets
  namespace: merch-store
type: Opaque
stringData:
  DB_AUTH_USER: "auth_user"
  DB_AUTH_PASSWORD: "auth_password"
  DB_STORE_USER: "store_user"
  DB_STORE_PASSWORD: "store_password"
  JWT_SECRET: "your-super-secret-jwt-key"